#!/usr/bin/lua

local total = 0
local lines = {}
local found = {}

for line in io.lines() do
	lines[#lines + 1] = tonumber(line)
end

while true do
	for _, line in pairs(lines) do
		found[total] = true
		total = total + line

		if found[total] then
			print(total)
			return
		end
	end
end

